source = conf/monitors.conf
source = conf/programs.conf
source = conf/autostart.conf
source = conf/env.conf
source = conf/style.conf
source = conf/input.conf
source = conf/keybinds.conf
source = conf/general.conf
