#################
### AUTOSTART ###
#################

# Hypr Ecosystem
exec-once = hyprlock
exec-once = hypridle
exec-once = hyprpaper

# Clipboard
exec-once = wl-paste --type text --watch cliphist store

# Notification daemon
exec-once = dunst

# Status bars
exec-once = qs

exec-once = systemctl --user start graphical-session.target
exec-once = systemctl --user start xdg-desktop-portal-hyprland

# Theme hot-reload watcher
exec-once = $HOME/dotfiles/homeconf/laptop/watch-theme.sh
