#################
### AUTOSTART ###
#################

# Hypr Ecosystem
exec-once = hyprpaper

# Clipboard
exec-once = wl-pase --type text --watch cliphist store

# Notification daemon
exec-once = dunst

# Status bars
exec-once = qs

exec-once = systemctl --user start graphical-session.target
