###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = wezterm --config-file ~/.config/wezterm/wezterm.lua
$fileManager = thunar
$menu = rofi -show drun
